default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  host: db
  database: myapp_development


test:
  <<: *default
  host: db
  database: myapp_test

production:
  <<: *default
  database: myapp_production
